# Generated by Django 5.2 on 2025-04-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Родитель', 'verbose_name_plural': 'Родители'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Проживающий', 'verbose_name_plural': 'Проживающие'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=10, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=10, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='Проживающий'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ФИО родителя/представителя'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='Проживающий'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issue_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_by',
            field=models.CharField(max_length=100, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='Проживающий'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_place',
            field=models.CharField(max_length=100, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория проживания'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='citizenship',
            field=models.CharField(max_length=50, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='contract_date',
            field=models.DateField(verbose_name='Дата заключения договора'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='contract_number',
            field=models.CharField(max_length=50, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='course',
            field=models.PositiveIntegerField(verbose_name='Курс обучения'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='institute',
            field=models.CharField(max_length=100, verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='payment_until',
            field=models.DateField(verbose_name='До какого числа оплачено'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вместимость комнаты(кол-во чел.)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер комнаты'),
        ),
    ]
